services:
  api:
    build:
      context: .
      target: production
    container_name: one-million-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@one-million-db:5432/onemillion?schema=public
      - JWT_SECRET=super_secret_jwt_key_12345
    depends_on:
      postgres:
        condition: service_healthy
    # Limite de recursos para optimizar el host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  postgres:
    image: postgres:15-alpine
    container_name: one-million-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=onemillion
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d onemillion" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
